server:
  port: ${PORT:8080}
spring:
  sql:
    init:
      mode: always
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
readers:
  usd:
    path: 'usd.csv'
    parallel-path: 'usd_parallel.csv'
    delimiter: ';'
    lines-to-skip: 1
    query: 'INSERT INTO historical_data (date, price) VALUES (:date, :price)'
    parallel-query: 'INSERT INTO historical_parallel_data (date, price) VALUES (:date, :price)'
    price-query: 'SELECT price FROM historical_data WHERE date = (SELECT MAX(date) FROM historical_data WHERE date <= ?)'
    price-parallel-query: 'SELECT price FROM historical_parallel_data WHERE date = (SELECT MAX(date) FROM historical_parallel_data WHERE price != 0 AND date <= ?)'
  business-type:
    path: 'business_types.csv'
    delimiter: ';'
    lines-to-skip: 1
    query: 'INSERT INTO business_types (business_type_id, initcap, active) VALUES (:businessTypeId, :initcap, :active) ON CONFLICT (business_type_id) DO UPDATE SET initcap = EXCLUDED.initcap, active = EXCLUDED.active;'
  sites:
    query: 'INSERT INTO sites (site_code, latitude, longitude) VALUES (:siteCode, :latitude, :longitude) ON CONFLICT (site_code) DO UPDATE SET latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude'
  customers:
    path: 'customers.csv'
    delimiter: ';'
    lines-to-skip: 1
    query: 'INSERT INTO customers (customer_id, email_address, name, business_type_id, default_site_code, archived, is_key_account, date_updated, date_created) VALUES (:customerId, :emailAddress, :name, :businessType.businessTypeId, :defaultSite.siteCode, :archived, :isKeyAccount, :dateUpdated, :dateCreated) ON CONFLICT (customer_id) DO UPDATE SET email_address = EXCLUDED.email_address, name = EXCLUDED.name, business_type_id = EXCLUDED.business_type_id, default_site_code = EXCLUDED.default_site_code, archived = EXCLUDED.archived, is_key_account = EXCLUDED.is_key_account, date_updated = EXCLUDED.date_updated, date_created = EXCLUDED.date_created'
  orders:
    path: 'orders.csv'
    delimiter: ';'
    lines-to-skip: 1
    query: 'INSERT INTO orders (order_id, batch_id, created_date, updated_date, submitted_date, delivery_date, customer_id, site_code, total, total_usd, total_shipping, total_shipping_usd, tracking_code, order_status, gmv_enabled, order_number, shipping_by_tracking, usd_official_listing, usd_parallel_listing) VALUES (:orderId, :batchId, :createdDate, :updatedDate, :submittedDate, :deliveryDate, :customer.customerId, :site.siteCode, :total, :totalUSD, :totalShipping, :totalShippingUSD, :trackingCode, :orderStatus, :gmvEnabled, :orderNumber, :shippingByTracking, :usdOfficialListing, :usdParallelListing) ON CONFLICT (order_id) DO UPDATE SET batch_id = EXCLUDED.batch_id, created_date = EXCLUDED.created_date, updated_date = EXCLUDED.updated_date, submitted_date = EXCLUDED.submitted_date, delivery_date = EXCLUDED.delivery_date, customer_id = EXCLUDED.customer_id, site_code = EXCLUDED.site_code, total = EXCLUDED.total, total_usd = EXCLUDED.total_usd, total_shipping = EXCLUDED.total_shipping, total_shipping_usd = EXCLUDED.total_shipping_usd, tracking_code = EXCLUDED.tracking_code, order_status = EXCLUDED.order_status, gmv_enabled = EXCLUDED.gmv_enabled, order_number = EXCLUDED.order_number, shipping_by_tracking = EXCLUDED.shipping_by_tracking, usd_official_listing = EXCLUDED.usd_official_listing, usd_parallel_listing = EXCLUDED.usd_parallel_listing'
batch:
  chunk-size: 500000
h2:
  datasource:
    driver: 'org.h2.Driver'
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    user: 'sa'
    password: ''
postgres:
  datasource:
    driver: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://ec2-44-206-204-65.compute-1.amazonaws.com:5432/d5m8gh8m2el2op'
    user: 'vkckyxcefmhvsi'
    password: '8e4032a71668e15dcd49ac184298ed23455225d0fe684ebcd3b8bbc62e297d6f'
